# Generated by Django 4.0.5 on 2022-07-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='comment',
            field=models.CharField(max_length=40, null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
    ]
